### ISSUE TITLE
Allow max_iter to be passed into fit_scores

### ISSUE THREAD

**Issue by griffincorriher** [miaohancheng/pysmatch#4]
In fit_model, max_iter is hard coded to 100. Would it be possible to allow the user to pass in max_iter to fit_scores? I am getting a failed to converge warning when model_type='linear':

```python 
**ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in**
    https://scikit-learn.org/stable/modules/preprocessing.html
```

**Comment by miaohancheng** [comment]
Thanks, I will consider this suggestion, but I’m curious about the size of your dataset. Has it still not converged after 100 iterations?

**Comment by miaohancheng** [comment]
Thank you for your feedback. You can try version `0.8` to see if it meets your needs.

**Comment by griffincorriher** [comment]
Hi, thank you for considering this. These are the size of the classes that I am working with.
n majority:~180000
n minority:~5000

**Comment by miaohancheng** [comment]
Your data is highly imbalanced, and relying solely on oversampling may lead to overfitting.
It’s recommended to apply some data augmentation techniques or adjust the ratio of positive and negative samples. 
The lack of convergence could also be due to insufficient differentiation between positive and negative samples. You might want to first examine the feature importance and analyze the data performance before proceeding with modeling.
